# Generated by Django 6.0 on 2025-12-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PriceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("final_location", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("city", models.CharField(max_length=100)),
                ("flat_weighted_avg", models.FloatField(blank=True, null=True)),
                ("office_weighted_avg", models.FloatField(blank=True, null=True)),
                ("others_weighted_avg", models.FloatField(blank=True, null=True)),
                ("shop_weighted_avg", models.FloatField(blank=True, null=True)),
                ("flat_50", models.FloatField(blank=True, null=True)),
                ("office_50", models.FloatField(blank=True, null=True)),
                ("others_50", models.FloatField(blank=True, null=True)),
                ("shop_50", models.FloatField(blank=True, null=True)),
                ("flat_75", models.FloatField(blank=True, null=True)),
                ("office_75", models.FloatField(blank=True, null=True)),
                ("others_75", models.FloatField(blank=True, null=True)),
                ("shop_75", models.FloatField(blank=True, null=True)),
                ("flat_90", models.FloatField(blank=True, null=True)),
                ("office_90", models.FloatField(blank=True, null=True)),
                ("others_90", models.FloatField(blank=True, null=True)),
                ("shop_90", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TestData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=10)),
                ("lastname", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
