# Generated by Django 6.0 on 2025-12-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=10)),
                ("lastname", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
