# Generated by Django 6.0 on 2025-12-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("priceapp", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pricedata",
            constraint=models.UniqueConstraint(
                fields=("final_location", "year", "city"),
                name="unique_location_year_city",
            ),
        ),
    ]
